### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lena-b1** [lena-b1/denis-website#1]
- [ ] În elementul meta sunt specificate: cuvintele-cheie ale site-ului, descrierea site-ului
pentru a fi ulterior ”vizibil” și motoarelor de căutare

- [ ] Toate resursele disponibile pe site sunt accesibile și se încarcă fără erori.
- [ ] Codul este bine formatat, corespunde normelor și nu este plagiat.

- [ ] Au fost utilizate corect filtrele de culoare, transformările, gradientele

- [ ] Contrastul culorilor text-background de pe site este adecvat – textul este citibil

- [ ] Dacă afacerea selectată are deja un logo, atunci acesta va fi prezent pe toate paginile

- [ ] Dimensiunea standard a fontului utilizat dă lizibilitate texului

- [ ] Au fost utilizate fonturi corespunzătoare, cel mult 2 fonturi folosite în site

- [ ] Stilizarea acoperă culori, font-uri, margini (borders), linii, înălțime, lățime, imagini
de fundal

- [ ] Imaginile sunt corect integrate, au același format

- [ ] Au fost amplasate elementele corect în pagina(ile) site-ului – utilizând și spațierea

- [x] Site-ul arata bine și este prezentat corect în diferite browsere (minimum 2) –
compatibilitate Cross-browser
- [x] Scrolling-ul este minimizat și este doar vertical - este realizată cerința de adaptare
a conținutului la diferite ecrane. Web site-ul este accesibil pe diferite dispozitive,
arată bine și este accesibil și pe dispozitive mobile
- [x] Componenta / pagina cu contacte va conține: nr de telefon, email, adresa fizică, o
hartă a locului sau a persoanei juridice promovate
- [x] Site-ul de promovare a unei persoane juridice (afaceri), trebuie să conțină paginile
sau componentele de bază: ”About Us”, ”Products / Services”, ”Contact Us”
- [x] Imaginile/Fișierele de stil/ Fișierele de scripting sunt puse în mapă separată, în
folderul-părinte al proiectului
- [x] Site-ul este organizat în mapă separată
- [x] Site-ul realizat corespunde vizual misiunii afacerii mici autohtone selecate
- [x] Sistemul de navigare prin site, meniul, este intuitiv, uşor de identificat

- [x] Sistemul de navigare este funcțional

- [x] Sistemul de navigare este prezent în toate paginile site-ului (dacă site-ul are la bază
mai multe pagini)

- [x] #2

- [x] Site-ul conține cel puțin o legătură externă

- [x] Sunt realizate referinte spre retelele de socializare – site-ul trebuie să posede
vizibilitate

- [x] Nu se accepta constructoare de site-uri (Wix, Wordpress, etc).
- [x] În timpul competiției nu se accepta folosirea unui șablon (cod deja pregătit) a altui
site
- [x] Au fost stilizate corect elementele sistemului de navigare
- [x] Website-ul creat va conține următorul disclaimer: Acest website a fost realizat în cadrul
competiției ”Tekwill Junior Ambassadors” organizată de proiectul ”Tekwill în Fiecare
Școală” și nu reflectă neapărat opinia proiectului.
